name: Test and build @novu/notification-center

on:
  workflow_call:

jobs:
  build_test:
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: '16.15.1'
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 7.5.0
          run_install: true

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: build,test
          projects: '@novu/notification-center'
          nxCloud: true

        with:
          name: notification-center-web-component
          path: packages/notification-center/dist/umd
